jobs:
  include:
    - stage: preflight
      env: TASK=travis-format

    - stage: libraries
      env: SBT_PROJECT=internal_model
    - env: SBT_PROJECT=display
    - env: SBT_PROJECT=elasticsearch

    - stage: services
      env: TASK=api-build

    - env: SBT_PROJECT=goobi_reader

    - env: SBT_PROJECT=reindex_worker

    - env: SBT_PROJECT=id_minter
    - env: SBT_PROJECT=ingestor
    - env: SBT_PROJECT=matcher
    - env: SBT_PROJECT=merger
    - env: SBT_PROJECT=recorder
    - env: SBT_PROJECT=transformer_miro
    - env: SBT_PROJECT=transformer_sierra

    - env: SBT_PROJECT=sierra_reader
    - env: SBT_PROJECT=sierra_bib_merger
    - env: SBT_PROJECT=sierra_item_merger
    - env: SBT_PROJECT=sierra_items_to_dynamo

    - env: SBT_PROJECT=snapshot_generator

    # TODO: Add a task for the Sierra adapter Lambdas
    # TODO: Add a task for the snapshot Lambdas

script:
  # Wait 45 minutes for the entire build to finish.  Primarily this stops the
  # build timing out if we're taking a really long time to compile something.
  # See https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
  - travis_wait 45 ./.travis/run_job.py

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

    - api/api/target

    - common/display/target
    - common/elasticsearch/target
    - common/elasticsearch_typesafe/target
    - common/internal_model/target

    - goobi_adapter/goobi_reader/target

    - pipeline/id_minter/target
    - pipeline/ingestor/target
    - pipeline/matcher/target
    - pipeline/merger/target
    - pipeline/recorder/target
    - pipeline/transformer/transformer_miro/target
    - pipeline/transformer/transformer_sierra/target

    - reindexer/reindex_worker/target

    - sierra_adapter/common/target
    - sierra_adapter/sierra_reader/target
    - sierra_adapter/sierra_bib_merger/target
    - sierra_adapter/sierra_item_merger/target
    - sierra_adapter/sierra_items_to_dynamo/target

    - snapshots/snapshot_generator/target

stages:
  - preflight
  - libraries
  - services

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip
  - chmod 600 id_rsa
  - mkdir -p ~/.aws
  - cp config ~/.aws/config
  - cp credentials ~/.aws/credentials

install:
  # We need this for the Elasticsearch Docker container to start
  # See https://github.com/travis-ci/travis-ci/issues/6534
  - sudo sysctl -w vm.max_map_count=262144

language: sh

services:
  - docker

dist: trusty

branches:
  only:
    - master

# Based on instructions from
# https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
before_cache:
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - sudo find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    - AWS_ECR_REPO=760097843905.dkr.ecr.eu-west-1.amazonaws.com

    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x
