index_sources:
  - legacy-works-indexed
  - new-works-indexed

ignore_fields:
  - debug.mergedTime
  - debug.indexedTime
  - display.precededBy
  - display.succeededBy
  - display.partOf[].totalDescendentParts
  - display.partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].totalDescendentParts
  - display.partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].partOf[].totalDescendentParts
  - display.parts[].totalDescendentParts
  - debug.mergeCandidates[].id.type
  - debug.redirectSources[].type
  - redirectTarget.type
  - aggregatableValues.production.dates[].id
  - aggregatableValues.production.dates[].label
  - aggregatableValues.languages[].label

sample_size: 100
loading_chunk_size: 100000

hash_bucket_count: 6

output_dir: data
